### ISSUE TITLE
Ungraceful error on attempting to open a password protected document

### ISSUE THREAD

**Issue by stephgosling** [sailfishos/sailfish-office#1]
Reported here: https://together.jolla.com/question/44849/bug-documents-app-error-message/ the text of which is:

I received an email with a password-protected .docx file attached. I didn't at the time realise the file was 'protected' and downloaded/opened the attachment anyway. That failed (which is fine, not expecting that support) but the error was rather nasty. For what it's worth, it wasn't orientation-aware so it's lucky that the 'OK' was visible so I could 'click' it. 

I'm assuming this is in Documents rather than the mail client, if I'm wrong please close :)

![20140606150014](https://cloud.githubusercontent.com/assets/1391834/3236885/edad514c-f0e1-11e3-9fbc-a567a623adda.png)

**Comment by VDVsx** [comment]
Fix in version 1.1.9. thanks to dcaliste.
