### ISSUE TITLE
Deleting multiple documents at the same time does not work

### ISSUE THREAD

**Issue by VDVsx** [sailfishos/sailfish-office#10]
DESCRIPTION:
============
When deleting multiple documents at the same time (selecting Delete from the context menu while an another document is already being deleted) is not possible. When the first document gets deleted, the document list gets refreshed and all other pending delete operations cancelled.
 
STEPS TO REPRODUCE:
===================
1) Start Documents
2) Long press on a document
3) Select Delete
4) While the remorse timer is active, long press on an another document
5) Select Delete
 
ACTUAL RESULT:
==============
Only the first document gets deleted because the list refreshes after the document gets deleted and other remorse timers get cancelled

EXPECTED RESULT:
================
Both documents get deleted

REPRODUCIBILITY: 100%

**Comment by anandrkris** [comment]
Sailors - Just wanted to share that we already have 3 reports of this issue.
https://together.jolla.com/question/38050/documents-app-buggy-while-deleting/ >>18 votes
https://together.jolla.com/question/79359/documents-only-one-item-can-be-deleted/ >> 5 votes 
https://together.jolla.com/question/86553/delete-multiple-documents-doesnt-work-as-expected/ >> 2 votes

**Comment by dcaliste** [comment]
Hello Rainemak, thanks for you reply. I've looked to the code, and the delete action comes from models/trackerdocumentprovider.cpp:184 that call removeAt() on the underlying model, which links to models/documentlistmodel.cpp:128. This function indeed call beginRemoveRows() and endRemoveRows() before calling removeAt() on the Qlist storing the DocumentListModelEntry.

So, it seems to me that there is no reset of the model. Would you have any suggestion to look at ?

**Comment by VDVsx** [comment]
Fixed in 1.1.8
