### ISSUE TITLE
Search looses focus when typing

### ISSUE THREAD

**Issue by dcaliste** [sailfishos/sailfish-office#33]
Hello,

   The pull request #29 has broken the search tool. Now, each time one press a letter, the list gets the focus and the keyboard disappears. How can one keep the focus on the search field ?

**Comment by VDVsx** [comment]
focus can be forced, in the search field:
focus: parent.focus
// this is needed for case a list changes inserting or removing elements
focusOutBehavior: FocusBehavior.KeepFocus

**Comment by dcaliste** [comment]
Thanks for your advice. I've tried but it doesn't work. I'm still trying to understand what differ from other cases where this is employed, currently have no clue. I'll ask for help if I can't figure it out in the coming days…

**Comment by dcaliste** [comment]
After trying to figure out what's different between my code and the one in the silica component gallery in the SDK, I gave up and try looking for the web : bingo ! https://lists.sailfishos.org/pipermail/devel/2013-December/002251.html

For reference, setting currentItem to -1 in the listview fix the issue.

**Comment by dcaliste** [comment]
Closed with PR #34.
