### ISSUE TITLE
Search should not be available when there are no documents

### ISSUE THREAD

**Issue by VDVsx** [sailfishos/sailfish-office#37]
If placeholder text is displayed pulley menu should not be visible.

**Comment by dcaliste** [comment]
Good point, as stated in https://sailfishos.org/develop/docs/silica/sailfish-application-pitfalls.html/ at the end of the page, I've added a visible attribute to the pull down menu.

**Comment by lukedirtwalker** [comment]
@VDVsx can be closed as it is fixed?
