### ISSUE TITLE
Go back after internal link

### ISSUE THREAD

**Issue by dcaliste** [sailfishos/sailfish-office#89]
That would be nice to have a UI action to go back to previous position in a PDF document after an internal goto link has been tapped. Use case is typically a goto link for a figure or a chapter reference that send some pages further, and after one has seen the figure, one would like to go back to his previous reading position in the text.

Would it be a good idea to have a back arrow in the new toolbar design that appears after internal link clicking ? IMHO, it would not be easily discoverable like that but less space eating than a back arrow always present.

Should we ask design or they are quite occupied already and this is a minor request ?

**Comment by pvuorela** [comment]
Should consult with design as it uses space from the toolbar.

After annotation buttons, there could still be space left for more buttons, but need to be careful. For comparison Adobe reader doesn't provide back/forward, but has support for creating bookmarks on the document.

If done, maybe with just one level of history, skipping forward button and maybe back button even disappearing when moving +-1 page away from link target. Just quick ideas.

**Comment by dcaliste** [comment]
> If done, maybe with just one level of history, skipping forward button and maybe back button even disappearing when moving +-1 page away from link target. Just quick ideas.

That's exactly my opinion, indeed. The use case is really the one described before : following a link for a side reading, and then go back to the main reading. If reading continue after the goto link, then the back button disappears.

> support for creating bookmarks on the document.

I was also thinking about this yesterday evening. They may have their places in the table of content page (*i.e.* the attached page) where one can navigate quickly in a document, but I didn't figure out how to intuitively create them. I was also wondering how to properly label them to be usefull. Possible use case: one read a 10 document and notice that a figure on page 4 is quite important. One selects some words in the figure caption (or the full caption) and make a bookmark for this selection. Then a listItem with the elipsized text of the bookmark is available in the ToC page for instance. The same if a paragraph in a long document looks of particular importance: selection -> bookmark. But it looks a bit of a double usage with the highlight annotation (except for the quick access in the ToC page). Should these two things be united (heighlight creating quick accesses) ?

What would be interesting also about bookmarks, would be the ability for the search field (in the document list) to search also on the bookmark labels. It converges with the discussion we had some time ago about the tagging of documents.

Well, well, well, all ideas and possibilities about bookmarks are not all clear for me, and I need to continue to think about them. I'll open a dedicated issue entry when these will be clearer in my mind.
